compile-pdf:
  stage: build
  image: blang/latex
  script:
    - make
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cd public
  artifacts:
    paths: 
      - public