compile-pdf:
  stage: build
  image: dregistry.gahr.dev/texlife-full
  script:
    - make
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cd public
  artifacts:
    paths: 
      - public