compile-pdf:
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin 
  stage: build
  image: dregistry.gahr.dev/texlife-full
  script:
    - make
  artifacts:
    paths:
      - "*.pdf"

pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.pdf public
    - cd public
  artifacts:
    paths: 
      - public